/**
 * Semantic icon map. Templates ask for `icon="pending"`, never import a Phosphor
 * glyph directly — renaming the underlying icon is one entry here.
 *
 * Imported from the SSR build so server components can render icons too.
 */
import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Buildings,
  Calendar,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChalkboardTeacher,
  ChartBar,
  ChartLineUp,
  CheckCircle,
  Clock,
  Coins,
  CurrencyNgn,
  Download,
  EnvelopeSimple,
  Exam,
  Eye,
  FileText,
  Funnel,
  Globe,
  GraduationCap,
  HandCoins,
  HandHeart,
  Handshake,
  Heart,
  House,
  Info,
  Lightbulb,
  List,
  Lock,
  MagnifyingGlass,
  MapPin,
  Paperclip,
  PencilSimple,
  Phone,
  Plus,
  Quotes,
  Receipt,
  SealCheck,
  ShieldCheck,
  SignOut,
  Sparkle,
  Student,
  Target,
  Trash,
  Tray,
  UploadSimple,
  UserCircle,
  Users,
  WarningCircle,
  WhatsappLogo,
  X,
  XCircle,
} from "@phosphor-icons/react/dist/ssr";
import type { Icon } from "@phosphor-icons/react";

export const ICONS = {
  // navigation
  home: House,
  dashboard: ChartBar,
  menu: List,
  close: X,
  back: ArrowLeft,
  forward: ArrowRight,
  external: ArrowUpRight,
  chevronLeft: CaretLeft,
  chevronRight: CaretRight,
  chevronDown: CaretDown,
  signOut: SignOut,
  search: MagnifyingGlass,
  filter: Funnel,

  // domain
  child: Student,
  children: Users,
  school: Buildings,
  results: Exam,
  teacher: ChalkboardTeacher,
  graduation: GraduationCap,
  pledge: HandCoins,
  contribution: Coins,
  naira: CurrencyNgn,
  disbursement: Receipt,
  giver: HandHeart,
  givers: Handshake,
  family: Heart,
  performance: ChartLineUp,
  profile: UserCircle,
  mission: Target,
  vision: Eye,
  idea: Lightbulb,
  globe: Globe,
  quote: Quotes,
  sparkle: Sparkle,
  transparency: SealCheck,
  safeguarding: ShieldCheck,
  lock: Lock,
  calendar: Calendar,
  empty: Tray,

  // contact
  phone: Phone,
  email: EnvelopeSimple,
  whatsapp: WhatsappLogo,
  location: MapPin,

  // actions
  add: Plus,
  edit: PencilSimple,
  delete: Trash,
  upload: UploadSimple,
  download: Download,
  view: Eye,
  document: FileText,
  attachment: Paperclip,

  // status
  complete: CheckCircle,
  pending: Clock,
  attention: WarningCircle,
  failed: XCircle,
  info: Info,
} satisfies Record<string, Icon>;

export type IconName = keyof typeof ICONS;
